-- CreateEnum
CREATE TYPE "SpotType" AS ENUM ('REGULAR', 'COMPACT', 'LARGE', 'MOTORCYCLE', 'ACCESSIBLE', 'ELECTRIC');

-- AlterTable
ALTER TABLE "parking_spots" ADD COLUMN     "column" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "row" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "spot_type" "SpotType" NOT NULL DEFAULT 'REGULAR';
